base00: &base00 "#{{base00-hex}}"
base01: &base01 "#{{base01-hex}}"
base02: &base02 "#{{base02-hex}}"
base03: &base03 "#{{base03-hex}}"
base04: &base04 "#{{base04-hex}}"
base05: &base05 "#{{base05-hex}}"
base06: &base06 "#{{base06-hex}}"
base07: &base07 "#{{base07-hex}}"
base08: &base08 "#{{base08-hex}}"
base09: &base09 "#{{base09-hex}}"
base0A: &base0A "#{{base0A-hex}}"
base0B: &base0B "#{{base0B-hex}}"
base0C: &base0C "#{{base0C-hex}}"
base0D: &base0D "#{{base0D-hex}}"
base0E: &base0E "#{{base0E-hex}}"

# Some colours are used dimmed, which (almost?) entirely negates the point of setting it, but we still set it to a sensible value in case that behaviour is changed in the future.

k9s:
  body:
    fgColor: *base05
    bgColor: default
    logoColor: *base0E
  prompt:
    fgColor: *base05
    bgColor: *base00
    suggestColor: *base09
    border:
      default: *base0D
      command: *base0B
  help:
    fgColor: *base05
    bgColor: *base00
    sectionColor: *base0A
    keyColor: *base0D
    numKeyColor: *base0E
  frame:
    title:
      fgColor: *base05
      bgColor: *base01
      highlightColor: *base09
      counterColor: *base0E
      filterColor: *base0D
    border:
      fgColor: *base03
      focusColor: *base04
    menu:
      fgColor: *base05 # dimmed
      keyColor: *base0D
      numKeyColor: *base0E
    crumbs:
      fgColor: *base05
      bgColor: *base01
      activeColor: *base02
    status:
      newColor: *base04
      modifyColor: *base0C
      addColor: *base0B
      pendingColor: *base0C
      errorColor: *base08
      highlightcolor: *base0E
      killColor: *base09
      completedColor: *base02
  info:
    fgColor: *base0D
    sectionColor: *base04
  views:
    table:
      fgColor: *base05
      bgColor: default
      markColor: *base0B
      header:
        fgColor: *base05
        bgColor: default
        sorterColor: *base0C
    xray:
      fgColor: *base05
      bgColor: default
      cursorColor: *base0B
      graphicColor: *base0E
    charts:
      bgColor: default
      defaultDialColors:
        - *base0E
        - *base08
      defaultChartColors:
        - *base0E
        - *base08
    yaml:
      keyColor: *base0D
      colonColor: *base0E
      valueColor: *base05
    picker:
      mainColor: *base05
      focusColor: *base07
      shortcutColor: *base07
    logs:
      fgColor: *base05
      bgColor: default
      indicator:
        fgColor: *base05
        bgColor: *base01
        toggleOnColor: *base0B
        toggleOffColor: *base0B # dimmed
  dialog:
    fgColor: *base05
    bgColor: default
    buttonFgColor: *base05
    buttonBgColor: *base0E
    buttonFocusFgColor: *base0A
    buttonFocusBgColor: *base0D
    labelFgColor: *base09
    fieldFgColor: *base05
