#!/usr/bin/env sh
# shellcheck disable=SC2059

color_grid() {
	colors

	format='%-9s'
	# shellcheck disable=SC2034,SC2154
	for name in $(echo "$color_names" | tr ' ' '\n'); do
		format="$format %-7s"
	done
	format="$format\\n"

	# shellcheck disable=SC2046
	printf "$format" '↓ bg fg →' $(echo "$color_names" | tr ' ' '\n')
	# shellcheck disable=SC2046,SC2154
	printf "$format" $(
		for bg_name in $(echo "$color_names" | tr ' ' '\n'); do
			echo "$bg_name"
			for fg_name in $(echo "$color_names" | tr ' ' '\n'); do
				printf '%s%s%s%s ' \
					"$(eval "echo \$color_bg_$bg_name")" \
					"$(eval "echo \$color_fg_$fg_name")" \
					'example' \
					"$color_reset"
			done
		done
	)
}

