#!/usr/bin/env sh

color_grid_true() {
	(
		set -e

		colors
		size=$(stty size)
		awk \
			-f "$HOME/.functions/color_grid_true.awk" \
			-v "width=${size#* }" \
			-v "height=${size% *}" \
			-v "saturation=${1:-100}" \
			-v "character=$2"
		read -r
	)
}
