#!/usr/bin/env sh

in_path() {
	case ":$PATH:" in
		*":$1:"*)
			return 0 # zero return code -> success
			;;
		*)
			return 1 # non-zero return code -> failure
			;;
	esac
}

prepend_to_path() {
	in_path "$1" && remove_from_path "$1"
	export PATH="$1:$PATH"
}

append_to_path() {
	in_path "$1" && remove_from_path "$1"
	export PATH="$PATH:$1"
}

# Usage: $0 directory-or-pattern [grep-flags]
remove_from_path() {
	PATH="$(echo "$PATH" | tr ':' '\n' | grep -v"${2:-xF}" "$1" | tr '\n' ':' | sed 's/^:\+//; s/::\+/:/g; s/:$//')"
	export PATH
}
