" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Load pathogen.
" This too has to happen before anything else, so we can be sure that all
" plugins and such are available for use in the vimrc files.
let &runtimepath = &runtimepath . ',' . finddir('bundle/pathogen', &runtimepath)
if has('nvim')
	execute pathogen#infect('bundle/{}', 'bundle-nvim/{}')
else
	execute pathogen#infect('bundle/{}', 'bundle-vim/{}')
endif

" Load the rest, in a single autogroup, so we can reload safely.
augroup vimrc
au!

runtime! rc/general.vim
runtime! rc/plugins.vim
runtime! rc/after.vim

augroup END
