" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Load pathogen.
" This too has to happen before anything else, so we can be sure that all
" plugins and such are available for use in the vimrc files.
let &runtimepath = &runtimepath . ',' . finddir('bundle/pathogen', &runtimepath)
if has('nvim')
	execute pathogen#infect('bundle/{}', 'bundle-nvim/{}')
else
	execute pathogen#infect('bundle/{}', 'bundle-vim/{}')
endif

" Define the autocmd group, so we can delete all autocommands set in the vimrc at once.
augroup vimrc

" Delete all autocommands previously defined in this group.
au!

" Load the rc files responsible for the core initialisation.
runtime! rc/general.vim
runtime! rc/plugins.vim

" Close the autocmd group.
augroup END

" Load the rc files responsible for the final touches.
runtime! rc/after.vim
