aliases:
  light: atelier-sulphurpool-light
  dark: solarflare
applications:
  bat:
    templates:
      - input: ./templates/bat.mustache.xml
        output: ~/.config/bat/themes/base16.tmTheme
    hook: bat cache --build
  dircolors:
    templates:
      - input: ./bundle/dircolors/templates/default.mustache
        output: ~/.config/base16/bundle/dircolors/templates/build.py
    hook: python ~/.config/base16/bundle/dircolors/templates/build.py | dircolors > ~/.profile.d/50_dircolors.local
  envvars:
    templates:
      - input: ./templates/envvars.mustache
        output: ~/.profile.d/50_base16.local
  fzf:
    templates:
      - input: ./bundle/fzf/templates/base16-default.mustache
        output: ~/.base16_theme_fzf
  i3:
    templates:
      - input: ./templates/i3.mustache
        output: ~/.config/i3/config
    hook: i3-msg reload
  k9s:
    templates:
      - input: ./templates/k9s.mustache.yaml
        output: ~/.config/k9s/skins/base16.yaml
  kitty:
    templates:
      - input: ./bundle/kitty/templates/default-256.mustache
        output: ~/.config/kitty/base16.conf
  polybar:
    templates:
      - input: ./bundle/polybar/templates/default.mustache
        output: ~/.config/polybar/base16.ini
    hook: polybar-msg cmd restart
  rofi:
    templates:
      - input: ./bundle/rofi/templates/default.mustache
        output: ~/.config/rofi/theme.rasi
  shell:
    templates:
      - input: ./bundle/shell/templates/base16.mustache
        output: ~/.zsh/rc/base16.local.zsh
  tmux:
    templates:
      - input: ./templates/tmux.jinja
        output: ~/.tmux/base16.conf
    hook: tmux source ~/.tmux/base16.conf
  neovim:
    templates:
      - input: ./templates/neovim.mustache.lua
        output: ~/.vim/colors/base16.lua
  vifm:
    dependsOn:
      - dircolors
    hook: source ~/.profile.d/50_dircolors.local; vifm-convert-dircolors -e > ~/.config/vifm/base16.vifm
  xresources:
    templates:
      - input: ./bundle/xresources/templates/base16.mustache
        output: ~/.Xresources.d/base16.local
    hook: xrdb -merge ~/.Xresources
